name: Set up NASM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: download
      run: wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/nasm-2.16.03.tar.gz
    - name: unpack
      run: tar xvfz nasm-2.16.03.tar.gz
    - name: show working directory
      run: echo `pwd`
    - name: compile
      run: |
        cd nasm-2.16.03
        ./configure
        make
    - name: install
      run: |
        cd nasm-2.16.03
        mkdir -p /opt/local/bin
        cp nasm /opt/local/bin
