jobs:
  test:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v1
    - name: Set up NASM
      with:
        version: # default is 2.16.01
        from-source: true
        platform: linux
